### ISSUE TITLE
Checking for DART gui libs : Not found

### ISSUE THREAD

**Issue by Hi-Ryan** [resibots/ite_v2#1]
In following the Installing the DART wrapper instructions, I encountered the following issues:
Checking for DART includes (including utils/urdf) : ok 
Checking for DART gui includes                    : Not found 
DART: Checking for optional Bullet includes       : ok 
Checking for DART libs (including utils/urdf)     : ok 
DART: Checking for Assimp                         : ok 
Checking for DART gui libs                        : Not found 
Checking for hexapod_controller includes          : ok 
['-Wall', '-std=c++11', '-O3', '-march=native', '-g']
'configure' finished successfully (0.145s)

And I have referred to your suggestions on the https://github.com/resibots/map_elites_hexapod_v2/issues/1.
So I am using DART v6.4 and installed freeglut3-dev.
But it still prompts "Checking for DART gui libs : Not found“

Any suggestions how to resolve this?

**Comment by costashatz** [comment]
> Any suggestions how to resolve this?

You need OpenSceneGraph for DART gui for our applications: install `libopenscenegraph-dev`..

**Comment by Hi-Ryan** [comment]
In fact, I have installed all dependencies through the DART website. http://dartsim.github.io/install_dart_on_ubuntu.html#install-optional-dependencies

**Comment by costashatz** [comment]
Could you give me the output of `ls /usr/local/include/dart/`, `ls /usr/local/include/dart/gui/` and `ls /usr/local/include/dart/gui/osg/` (change `/usr/local/include/` to wherever you have installed DART)?

**Comment by Hi-Ryan** [comment]
dong@dong-ITE:~$ ls /usr/local/include/dart/
collision  config.hpp  dart.hpp  external     lcpsolver  optimizer  simulation
common     constraint  dynamics  integration  math       planning   utils
dong@dong-ITE:~$ ls /usr/local/include/dart/gui/
ls: cannot access /usr/local/include/dart/gui/: No such file or directory
dong@dong-ITE:~$ ls /usr/local/include/dart/gui/osg/
ls: cannot access /usr/local/include/dart/gui/osg/: No such file or directory
dong@dong-ITE:~$ sudo apt-get install libopenscenegraph-dev
[sudo] password for dong: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenscenegraph-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 379 not upgraded.

**Comment by costashatz** [comment]
Can you please uninstall DART (cd to `/dart_src/build` and `sudo make uninstall`)? Remove the `build` folder (`rm -rf build` from the dart source directory) and re-install DART?

```bash
cd dart
git checkout release-6.4

mkdir build
cd build
cmake -DDART_ENABLE_SIMD=ON ..
make -j4
sudo make install
```

Then try again to ls the gui folders.. If they are still not there, please make a `cmake -DDART_ENABLE_SIMD=ON -DDART_VERBOSE=ON ..` and give me the output. If they are there, retry  our code..

**Comment by Hi-Ryan** [comment]
Thanks for your help. It works now.

**Comment by costashatz** [comment]
Great! Let us know if you have any other issue..

**Comment by henryclever** [comment]
I also have this issue. However, I have tried the fix stated above and it does not solve it. Can you provide a tip?
Thanks!

**Comment by costashatz** [comment]
> I also have this issue. However, I have tried the fix stated above and it does not solve it. Can you provide a tip?
> Thanks!

Can you give me the output of the following?

```bash
./waf clean
./waf configure
```
