### ISSUE TITLE
Checking for NLOpt C++ libs (optional)         : Not found 

### ISSUE THREAD

**Issue by Hi-Ryan** [resibots/ite_v2#2]
Excuse me.
I have other issue.
When I excute "Configure the experiment: ./waf configure --exp ite_v2", I encountered the following issues:
Checking Intel MKL includes (optional)         : Not found 
Checking for NLOpt C++ includes (optional)     : /usr/local/include 
Checking for NLOpt C++ libs (optional)         : Not found in ['/home/dong/resibots/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu/'] 
Checking for libcmaes includes (optional)      : Not found in ['/usr/local/include', '/usr/include'] 

I would like to ask if it is necessary to install MKL and how to solve 'NLOpt C++ libs' is not found

**Comment by jbmouret** [comment]
MKL is not required. NLopt is not required for ite_v2, but if you want to have it you might need to specify where it is installed. Where is `libnlopt_cxx.so` in your system?

**Comment by Hi-Ryan** [comment]
I did not install libcmaes, MKL, and nlopt. But I succeeded in compiling the experiment. But when I run it, I encountered the following issues:

[26/26] Linking build/exp/ite_v2/hexapod_graphic
Waf: Leaving directory `/home/dong/resibots/limbo/build'
'build' finished successfully (2m29.100s)
dong@dong-ITE:~/resibots/limbo$ ./build/exp/ite_v2/hexapod_simu path_to_archive [-l id_of_to_be_removed] [-n number_of_BO_iterations]
Loading text file...
ERROR: Could not load the archive.
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
dong@dong-ITE:~/resibots/limbo$ ./build/exp/ite_v2/hexapod_graphic path_to_archive [-l id_of_to_be_removed] [-n number_of_BO_iterations]
Loading text file...
ERROR: Could not load the archive.
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)

Do you have any suggestions how to resolve this?

**Comment by jbmouret** [comment]
As said in the error message, you need to give an archive of pre-evolved controllers (evolved with map-elites). I suppose we have some of them for the hexapod. @costashatz ?

**Comment by Hi-Ryan** [comment]
emm..But I never found the archives folder.

**Comment by costashatz** [comment]
> emm..But I never found the archives folder.

Sorry about this.. I will upload one archive later today or tomorrow at some point. Alternatively, you can generate your own with [hexapod_map_elites](https://github.com/resibots/map_elites_hexapod_v2).

**Comment by costashatz** [comment]
@Hi-Ryan I just pushed an archive that you use for trying..
