### ISSUE TITLE
*** stack smashing detected ***: <unknown> terminated

### ISSUE THREAD

**Issue by AranBSmith** [resibots/ite_v2#4]
Hi, I have run into a road block. 

I get to the `./waf configure --exp ite_v2 --no-native` and the `./waf --exp ite_v2 --no-native` commands, I use the no native flag as otherwise I immediately run into segmentation fault.

I have pinned a `*** stack smashing detected ***: <unknown> terminated` message to when `global::global_robot = std::make_shared<hexapod_dart::Hexapod>(robot_file, damages);` is called in the `init_simu` method.

Not too sure where to go from here.. hope you can help!

**Comment by costashatz** [comment]
Hey..

This is because you are using a new Ubuntu distribution and an old version of DART (mandatory for the current state of the repo). See https://github.com/dartsim/dart/issues/1035 and https://github.com/dartsim/dart/pull/1115.

Just use it without the native flags.. You should not gain too much anyway..

I should update the repo at some point to use the latest DART, but I do not have a lot of time at the moment. It is on my TODO list though..

**Comment by AranBSmith** [comment]
I see, thanks for the feedback. 

I'm keen on running this project as I will be doing something similar starting from June.. The best thing for me now would be to downgrade my dist. 

Which version should I downgrade to?

**Comment by costashatz** [comment]
> I'm keen on running this project as I will be doing something similar starting from June.. The best thing for me now would be to downgrade my dist.
> 
> Which version should I downgrade to?

It should work without the native flags.. And this should be okay both performance-wise and result-wise. If I understood well, this is running without the native flags, no?

**Comment by AranBSmith** [comment]
I ran it without the native flags, but instead I get `Segmentation fault (core dumped)` at the same place it seems.

**Comment by costashatz** [comment]
> I ran it without the native flags, but instead I get `Segmentation fault (core dumped)` at the same place it seems.

Did you recompile DART without the native flags? Just do `cmake -DDART_ENABLE_SIMD=OFF ..` when configuring..

**Comment by AranBSmith** [comment]
No, I kept DART vanilla.. does `cmake -DDART_ENABLE_SIMD=OFF ..` give me that setting?

**Comment by costashatz** [comment]
> No, I kept DART vanilla.. does `cmake -DDART_ENABLE_SIMD=OFF ..` give me that setting?

Make sure you uninstall DART and re-install.

Also clean your waf build directories: `./waf distclean`

**Comment by AranBSmith** [comment]
Great, got it to work! Sorry for the trouble.
